version: 2

python:
    install:
      - requirements: docs/requirements.txt

build:
    os: ubuntu-24.04
    tools:
        python: "3.13"
    commands:
        - ./doc/build_doc.sh ${SPHINX_PROJECT}
