name: Github CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Create and activate conda environment
      run: |
        # Assuming $CONDA is set to your miniconda root; otherwise, use $(conda info --base)
        conda create -n myenv -f pgmpy_env.yml
        conda activate myenv
        pip install -e .
        
      shell: bash
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest & coverage
      run: |
        pytest --cov --cov-branch --cov-report=xml
        pytest --cov --junitxml=junit.xml -o junit_family=legacy
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
