name: Auto Format Python Code

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}  # Checkout the branch of the PR

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install formatting tools
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black
        run: |
          black .

      - name: Commit and push formatting changes
        run: |
          # Check if any files have been modified
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add .
            git commit -m "Auto apply black [skip ci]"
            git push origin ${{ github.head_ref }}  # Push changes to the same PR branch
          else
            echo "No formatting changes detected."
          fi
